name: CI

on:
  pull_request:
    branches:  
      - develop
      - master


jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.9-management    
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672:5672
          - 15672:15672

    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      env:
        POSTGRES_CONNECTION_STRING: "Host=localhost;Port=5432;Database=english_site;Username=big;Password=${{ secrets.POSTGRES_PASSWORD }}"
        RABBITMQ_CONNECTION_STRING: "amqp://guest:guest@localhost:5672"
      run: |
        dotnet test AuthIntegrationTests
        dotnet test AuthTest 
        
    - name: Fail if tests fail
      if: ${{ failure() }}
      run: exit 1

